# ===============================
# Application
# ===============================
spring.application.name=chat
server.port=9090

# ===============================
# Logging
# ===============================
logging.level.org.springframework.web=DEBUG

# ===============================
# MongoDB
# ===============================
spring.data.mongodb.uri=mongodb://localhost:27017/chatdb
spring.data.mongodb.database=chatdb

# REQUIRED for transactions (replica set)
spring.data.mongodb.auto-index-creation=true

# ===============================
# WhatsApp Cloud API
# ===============================
chat.whatsapp.token=EAAWzb8xNArsBQkZAyxSfw7vCz7vUTCqcocNTVPTpmDOYAoppQGwSAhY5AC2ftu4ZBC6qOGhEx45FWDXIgZBy8AfXsUemBAlZB3hQbrykl6uMwYMZC5CnbvRZCS9f8lw6zGa7nUuwjmsbtTHTq1jwXWsZBkw56BhZCFISEtN31xKFL2c1FWuGIRfU3Q1eO5jZAIWMC9dCZC4NH3aZCTFUDmLPpdQZAA4lGZANPEs3wjjppfNfbys4CgXEeRELbpjK8yKwK3ZBMmC7L5O0FZAt0zV2gZAUwclY
chat.whatsapp.phone-id=877207475481096
chat.whatsapp.graph-url=https://graph.facebook.com/v18.0
chat.session.timeout-seconds=900
# ===============================
# OpenAI (optional, future use)
# ===============================
openai.api-key=YOUR_OPENAI_API_KEY

# ===============================
# REDIS CONFIGURATION
# ===============================

spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=
spring.data.redis.timeout=6000

# Lettuce Pool Config
spring.data.redis.lettuce.pool.max-active=50
spring.data.redis.lettuce.pool.max-idle=15
spring.data.redis.lettuce.pool.min-idle=5
spring.data.redis.lettuce.pool.max-wait=3000

chat.external.doctor-service-url=http://doctor-service
chat.external.slot-service-url=http://slot-service
