# Server Configuration
server.port=8082

# Eureka Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

eureka.client.enabled=false
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false


# Spring Application
spring.application.name=auth-service

# Spring Cloud Config
spring.cloud.config.import-check.enabled=false

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/auth-service

# Custom ATS Properties
ats.mongodburi=localhost
ats.mongodbPort=27017
ats.environment=dev
ats.mongoDatabase=auth-service
ats.collection=authInfo

#JWT_SECRET=your-secret-ke
jwt.secret=ARNAN_AUTH_SERVICE_ULTRA_SECURE_SECRET_2026!!

