spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - ${CORS_ALLOWED_ORIGIN_1:http://localhost:4200}
              - ${CORS_ALLOWED_ORIGIN_2:http://127.0.0.1:4200}
              - ${CORS_ALLOWED_ORIGIN_3:https://dev.tridlio.com}
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600
      discovery:
        locator:
          enabled: false
      routes:
        - id: auth-service
          uri: http://chatbot-app-auth-service.chatbot-app-local:8082
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: book-appointment
          uri: http://chatbot-app-book-appointment.chatbot-app-local:9091
          predicates:
            - Path=/book/**
          filters:
            - StripPrefix=1
        - id: chat-service
          uri: http://chatbot-app-chat.chatbot-app-local:9090
          predicates:
            - Path=/chat/**
          filters:
            - StripPrefix=1
        - id: i18n-service
          uri: http://chatbot-app-i18n-service.chatbot-app-local:9092
          predicates:
            - Path=/i18n/**
          filters:
            - StripPrefix=1

server:
  port: 8080

eureka:

  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

oauth2:
  jwt:
    secret: ${JWT_SECRET:ARNAN_AUTH_SERVICE_ULTRA_SECURE_SECRET_2026!!}
