# ===============================
# APP
# ===============================
spring.application.name=userservice
server.port=8083

# ===============================
# MONGODB (Spring managed)
# ===============================
spring.data.mongodb.uri=mongodb://localhost:27017/ats
spring.data.mongodb.database=ats

# ===============================
# REDIS
# ===============================
spring.data.redis.host=localhost
spring.data.redis.port=6379

# ===============================
# JWT CONFIG (ENV based secret)
# ===============================
#app.jwt.secret=${JWT_SECRET}
app.jwt.secret=TestDevelopjwtSecretkeyTestDevelopjwtSecretkey123TestDevelopjwtSecretkey@!
app.jwt.access.expiry=900000
app.jwt.refresh.expiry=604800000

# ===============================
# LOGGING
# ===============================
logging.level.root=INFO
logging.level.com.arnan.userservice=DEBUG