spring.application.name=auth-service
server.port=8081
 
# MongoDB connection
spring.data.mongodb.uri=mongodb+srv://sanjeevndesai_db_user:Sanpug%402601@chatbot.wqqueab.mongodb.net/?authMechanism=DEFAULT
 
# JWT secret (temporary)
jwt.secret=mySuperSecretKey123456789
jwt.expiration=86400000  # 24 hours in milliseconds
 
# Optional: Enable detailed logging
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG