spring.application.name=i18n-service
server.port=8080

spring.data.mongodb.uri=mongodb://localhost:27017/i18n_db
spring.data.mongodb.database=i18n_db

logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.mongodb.driver=DEBUG

# Admin user for security
app.security.admin.username=admin
app.security.admin.password=admin123
